Repository UOX3DevTeam/UOX3, pull requests merged in 2025-04, with the labels that each got.

#277 AOS Properties Regeneration
  data/dfndata/items/gear/armor/base_armor.dfn
  data/dfndata/items/gear/clothing/aos_clothing.dfn
  data/dfndata/items/gear/clothing/clothing.dfn
  data/dfndata/items/gear/clothing/footwear.dfn
  data/dfndata/items/gear/clothing/headwear.dfn
  data/dfndata/items/gear/clothing/td_footwear.dfn
  data/dfndata/race/races.dfn
  data/dictionaries/dictionary.CSY
  data/dictionaries/dictionary.ENG
  data/dictionaries/dictionary.FRE
  data/dictionaries/dictionary.GER
  data/dictionaries/dictionary.ITA
  data/dictionaries/dictionary.POL
  data/dictionaries/dictionary.PTG
  data/dictionaries/dictionary.SPA
  data/dictionaries/dictionary.ZRO
  data/js/commands/targeting/get.js
  data/js/commands/targeting/set.js
  data/js/skill/animallore.js
  data/js/skill/meditation.js
  data/uox.ini
  docs/assets/css/style.css
  docs/index.html
  docs/jsdocs.html
  make/VS2017/uox3.vcxproj
  source/CPacketSend.cpp
  source/Changelog.txt
  source/SEFunctions.cpp
  source/StringUtility.cpp
  source/UOXJSMethods.cpp
  source/UOXJSPropertyEnums.h
  source/UOXJSPropertyFuncs.cpp
  source/UOXJSPropertySpecs.h
  source/cBaseObject.cpp
  source/cBaseObject.h
  source/cChar.cpp
  source/cItem.cpp
  source/cItem.h
  source/cRaces.cpp
  source/cRaces.h
  source/cServerData.cpp
  source/cServerData.h
  source/cSocket.cpp
  source/cVersionClass.cpp
  source/combat.cpp
  source/combat.h
  source/enums.h
  source/items.cpp
  source/npcs.cpp
  source/skills.cpp
  source/ssection.cpp
  source/ssection.h
  source/townregion.cpp
  source/uox3.cpp
Labels: Changes Requested

#363 Tooltip sorting
  docs/assets/images/aos_combat_books.png
  docs/assets/images/basic_tooltips_only.png
  docs/assets/images/default_tooltips.png
  docs/assets/images/oldschool_tooltip.png
  docs/index.html
  docs/jsdocs.html
  source/CPacketSend.cpp
  source/CPacketSend.h
  source/Changelog.txt
  source/typedefs.h
Labels: enhancement, Ready for Review

#364 Misc Fixes and Updates
  README.md
  data/dfndata/items/gear/armor/base_armor.dfn
  data/dfndata/items/gear/armor/leather_armor/leather.dfn
  data/dfndata/npc/reptiles.dfn
  data/dfndata/race/races.dfn
  data/js/commands/custom/repeatingcmds.js
  data/js/commands/targeting/add.js
  data/js/commands/targeting/get.js
  data/js/commands/targeting/tele.js
  data/js/commands/targeting/tweak.js
  data/js/item/archerybutte.js
  data/js/npc/ai/vendor_bdo_dispenser.js
  data/js/server/global.js
  data/js/server/misc/furniture_smartturn.js
  data/js/server/network/0xDF_buffBar.js
  data/js/skill/healing.js
  data/js/skill/hiding.js
  data/uox.ini
  docs/index.html
  docs/jsdocs.html
  source/CPacketSend.cpp
  source/Changelog.txt
  source/SEFunctions.cpp
  source/UOXJSMethods.cpp
  source/UOXJSMethods.h
  source/UOXJSPropertyEnums.h
  source/UOXJSPropertyFuncs.cpp
  source/UOXJSPropertySpecs.h
  source/cChar.cpp
  source/cChar.h
  source/cItem.cpp
  source/cPlayerAction.cpp
  source/cRaces.cpp
  source/cRaces.h
  source/cScript.cpp
  source/cScript.h
  source/cServerData.cpp
  source/cServerData.h
  source/calcfuncs.cpp
  source/magic.cpp
  source/skills.cpp
  source/skills.h
  source/ssection.cpp
  source/ssection.h
  source/townregion.cpp
  source/townregion.h
  source/weight.cpp
Labels: enhancement, bugfix, Ready for Review
