Repository UOX3DevTeam/UOX3, pull requests merged in 2025-05, with the labels that each got.

#367 Dropping Gold Fix
  data/js/npc/ai/guildmaster.js
  data/js/npc/ai/vendor_bdo_dispenser.js
  source/Changelog.txt
Labels: bugfix, Ready for Review

#359 UO SE Npcs
  data/dfndata/npc/animals.dfn
  data/dfndata/npc/daemons.dfn
  data/dfndata/npc/humanoids_base.dfn
  data/dfndata/npc/mounts.dfn
  data/dfndata/npc/npc_se/animals_se.dfn
  data/dfndata/npc/npc_se/daemons_se.dfn
  data/dfndata/npc/npc_se/humanoids_se.dfn
  data/dfndata/npc/npc_se/mounts_se.dfn
  data/dfndata/npc/npc_se/undead_se.dfn
  data/dfndata/npc/undead.dfn
  source/Changelog.txt
Labels: enhancement, Ready for Review

#374 Healing Overhaul, fixes for mana regen, skill caps
  data/dictionaries/dictionary.CSY
  data/dictionaries/dictionary.ENG
  data/dictionaries/dictionary.FRE
  data/dictionaries/dictionary.GER
  data/dictionaries/dictionary.ITA
  data/dictionaries/dictionary.POL
  data/dictionaries/dictionary.PTG
  data/dictionaries/dictionary.SPA
  data/dictionaries/dictionary.ZRO
  data/js/commands/custom/misc-cmd.js
  data/js/commands/targeting/set.js
  data/js/commands/targeting/xwalk.js
  data/js/server/global.js
  data/js/skill/healing.js
  data/js/skill/healing_slip.js
  docs/jsdocs.html
  source/Changelog.txt
  source/UOXJSMethods.cpp
  source/cChar.cpp
  source/cScript.cpp
  source/cScript.h
  source/movement.cpp
  source/skills.cpp
  source/skills.h
  source/uox3.cpp
Labels: enhancement, bugfix

#376 Fix for skill calculation and int contribution to skill
  source/Changelog.txt
  source/skills.cpp
Labels: bugfix
